<a href="https://colab.research.google.com/github/chingyaousf/Intern-project-2023/blob/main/scripts/MLpredictionDep_05_Model_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing Libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [ ]:
# Loading the Dataset
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table.csv")
data

,DepMap_ID,A1BG (1) Exp,A1CF (29974) Exp,A2M (2) Exp,A2ML1 (144568) Exp,A3GALT2 (127550) Exp,A4GALT (53947) Exp,A4GNT (51146) Exp,AAAS (8086) Exp,AACS (65985) Exp,...,ZYG11A (440590) Exp,ZYG11B (79699) Exp,ZYX (7791) Exp,ZZEF1 (23140) Exp,ZZZ3 (26009) Exp,EIF2AK3 (9451) Dep,MYC (4609) Dep,NQO1 (1728) Dep,SF3B1 (23451) Dep,SQSTM1 (8878) Dep
0,ACH-000001,3.116032,0.056584,0.226509,0.111031,0.000000,1.035624,0.176323,5.700440,4.144046,...,3.282440,2.797013,6.821455,3.010780,4.381975,0.018546,0.807414,0.076613,1.000000,0.020657
1,ACH-000004,4.178715,0.000000,0.214125,0.344828,0.070389,0.097611,0.000000,6.336819,3.231125,...,0.014355,2.032101,7.002252,3.444932,4.910733,0.044907,0.999985,0.061617,1.000000,0.049385
2,ACH-000005,4.003602,0.014355,0.137504,0.014355,0.000000,0.028569,0.000000,6.337176,3.781360,...,0.014355,2.761285,6.826421,3.524816,5.592457,0.009301,1.000000,0.049535,0.994004,0.015969
3,ACH-000007,0.137504,1.405992,0.201634,0.000000,0.000000,0.014355,0.000000,5.431289,4.300856,...,0.014355,1.989139,6.332708,3.673556,3.469886,0.058868,0.999620,0.036902,0.999886,0.041706
4,ACH-000009,1.464668,3.586164,0.250962,0.000000,0.042644,4.525443,0.000000,5.674122,4.510962,...,1.356144,2.956057,7.853185,3.442280,3.351911,0.040590,0.979828,0.006602,0.973598,0.034535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,ACH-002785,1.967169,0.000000,2.198494,0.000000,0.000000,1.490570,0.000000,5.300490,4.314697,...,0.014355,4.173127,6.560256,2.969012,5.276869,0.038095,0.701928,0.161286,1.000000,0.136197
1001,ACH-002800,3.847997,0.000000,5.899901,0.321928,0.000000,3.206331,0.000000,5.831877,3.822730,...,0.622930,3.084064,6.596935,3.177918,4.847997,0.177952,0.462993,0.054260,1.000000,0.022899
1002,ACH-002834,1.819668,0.014355,0.014355,0.201634,0.000000,2.912650,0.028569,5.646451,4.547820,...,1.400538,2.568032,6.953498,3.087463,4.226509,0.002074,0.911326,0.022301,0.998623,0.013754
1003,ACH-002847,2.990955,0.000000,7.608440,0.014355,0.000000,0.584963,0.000000,5.104337,4.228819,...,1.480265,2.748461,7.432041,2.903038,4.660495,0.161273,0.704900,0.184386,0.999903,0.058351
1004,ACH-002926,3.189034,0.000000,9.335390,0.014355,0.000000,0.000000,0.014355,5.204376,4.405992,...,0.014355,2.776104,5.182295,2.956057,3.785551,0.017135,0.963046,0.022057,0.998453,0.055990

In [ ]:
# Loading the Dataset
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table_modified.csv")

data

,DepMap_ID,AAK1 (22848) Exp,ABCA4 (24) Exp,ABCB6 (10058) Exp,ABCD3 (5825) Exp,ABI2 (10152) Exp,ABLIM2 (84448) Exp,ACAD8 (27034) Exp,ACAP3 (116983) Exp,ACER3 (55331) Exp,...,ZNF862 (643641) Exp,ZNFX1 (57169) Exp,ZRANB2 (9406) Exp,ZYG11B (79699) Exp,ZYX (7791) Exp,EIF2AK3 (9451) Dep,MYC (4609) Dep,NQO1 (1728) Dep,SF3B1 (23451) Dep,SQSTM1 (8878) Dep
0,ACH-000001,3.078951,2.443607,4.811985,4.746313,5.388534,1.510962,2.918386,4.514753,5.980025,...,2.629939,4.003602,6.157044,2.797013,6.821455,0.018546,0.807414,0.076613,1.000000,0.020657
1,ACH-000004,2.292782,0.713696,4.973152,4.727920,5.187055,0.000000,6.191997,3.166715,3.648465,...,1.560715,2.904966,7.344917,2.032101,7.002252,0.044907,0.999985,0.061617,1.000000,0.049385
2,ACH-000005,2.625270,0.163499,5.231509,5.802452,5.328406,0.028569,5.561632,2.464668,4.025029,...,1.700440,3.166715,7.609179,2.761285,6.826421,0.009301,1.000000,0.049535,0.994004,0.015969
3,ACH-000007,1.970854,0.070389,3.392317,4.532940,3.499527,2.386811,4.410070,4.799605,2.283922,...,2.435629,3.051372,5.645010,1.989139,6.332708,0.058868,0.999620,0.036902,0.999886,0.041706
4,ACH-000009,3.397803,0.070389,5.590662,5.454834,4.841470,0.084064,5.183883,4.221877,3.549669,...,1.395063,4.263786,5.151372,2.956057,7.853185,0.040590,0.979828,0.006602,0.973598,0.034535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,ACH-002785,3.819668,0.238787,3.730096,5.890933,5.172728,0.189034,2.695994,1.895303,2.313246,...,2.773996,4.753284,6.036064,4.173127,6.560256,0.038095,0.701928,0.161286,1.000000,0.136197
1001,ACH-002800,4.034744,1.967169,2.805292,5.292414,4.761817,0.731183,4.161081,1.910733,3.206331,...,2.408712,3.614710,5.499846,3.084064,6.596935,0.177952,0.462993,0.054260,1.000000,0.022899
1002,ACH-002834,4.133399,1.786596,3.226509,4.999098,4.737146,0.214125,3.351911,2.464668,2.799087,...,0.887525,4.932156,5.254367,2.568032,6.953498,0.002074,0.911326,0.022301,0.998623,0.013754
1003,ACH-002847,3.396434,0.400538,3.379898,4.888500,4.164304,0.042644,2.482848,3.649615,6.646451,...,1.925999,3.484138,5.189825,2.748461,7.432041,0.161273,0.704900,0.184386,0.999903,0.058351
1004,ACH-002926,3.033863,0.000000,4.672991,4.822730,4.914565,0.000000,3.509696,3.845992,3.496974,...,2.516015,3.512227,5.825531,2.776104,5.182295,0.017135,0.963046,0.022057,0.998453,0.055990

In [ ]:
# Loading the Dataset
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/filtered_arranged_table_modified_03.csv")

data

,DepMap_ID,ARHGAP29 (9411) Exp,ARL4C (10123) Exp,BCAR1 (9564) Exp,BCAR3 (8412) Exp,BCL2 (596) Exp,BCL2L1 (598) Exp,CCND1 (595) Exp,CCND2 (894) Exp,CCND3 (896) Exp,...,YAP1 (10413) Exp,ZEB1 (6935) Exp,ZEB2 (9839) Exp,ZFP36L1 (677) Exp,ZNF217 (7764) Exp,EIF2AK3 (9451) Dep,MYC (4609) Dep,NQO1 (1728) Dep,SF3B1 (23451) Dep,SQSTM1 (8878) Dep
0,ACH-000001,7.570994,3.923149,4.506526,3.407353,0.903038,6.933573,7.437877,0.042644,4.375735,...,4.981853,0.124328,0.226509,5.612058,4.915999,0.018546,0.807414,0.076613,1.000000,0.020657
1,ACH-000004,0.189034,0.084064,0.250962,0.475085,1.361768,7.527399,1.056584,4.017031,9.091753,...,0.150560,0.176323,6.326609,4.339850,3.040892,0.044907,0.999985,0.061617,1.000000,0.049385
2,ACH-000005,0.263034,0.097611,0.214125,0.344828,2.536053,7.314787,2.295723,5.225352,8.802387,...,0.201634,0.555816,6.549207,4.202418,3.782409,0.009301,1.000000,0.049535,0.994004,0.015969
3,ACH-000007,1.855990,4.037382,4.491212,2.327687,0.150560,6.578335,5.198494,4.442943,4.533563,...,5.324091,0.650765,0.070389,6.787641,3.363171,0.058868,0.999620,0.036902,0.999886,0.041706
4,ACH-000009,3.635754,5.088311,5.914565,2.204767,1.378512,8.462748,7.428611,3.875780,4.568032,...,7.003040,0.070389,0.111031,4.984589,4.461398,0.040590,0.979828,0.006602,0.973598,0.034535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,ACH-002785,6.633286,3.422233,2.541019,5.982537,0.985500,6.346070,5.191010,0.000000,4.560104,...,4.974988,5.261907,4.336997,6.478487,6.109570,0.038095,0.701928,0.161286,1.000000,0.136197
1001,ACH-002800,5.783719,5.549977,3.618239,4.852998,0.985500,5.913608,6.467116,4.744699,5.634593,...,5.967399,4.552746,3.080658,6.238214,4.553361,0.177952,0.462993,0.054260,1.000000,0.022899
1002,ACH-002834,5.003152,6.382667,4.006298,5.301222,1.250962,4.745775,6.474760,2.244887,6.387845,...,5.149341,3.415488,4.882643,6.464668,4.486714,0.002074,0.911326,0.022301,0.998623,0.013754
1003,ACH-002847,3.976364,5.433961,4.526069,5.730368,1.356144,6.513491,10.967010,0.000000,5.676098,...,9.930811,3.286881,4.714246,5.561632,4.095080,0.161273,0.704900,0.184386,0.999903,0.058351
1004,ACH-002926,2.189034,4.617063,2.244887,1.327687,4.367371,5.206331,8.036174,0.565597,4.807870,...,5.113117,0.042644,5.296090,6.658783,4.397803,0.017135,0.963046,0.022057,0.998453,0.055990

In [ ]:
from numpy import true_divide
# Cleaning Column Names
clean_column_names = {}
for column in data.columns:
    clean_column_names[column] = column.strip().replace(' ', '_').replace('(', '').replace(')', '')

data.rename(columns=clean_column_names, inplace=True)

data

,DepMap_ID,AAK1_22848_Exp,ABCA4_24_Exp,ABCB6_10058_Exp,ABCD3_5825_Exp,ABI2_10152_Exp,ABLIM2_84448_Exp,ACAD8_27034_Exp,ACAP3_116983_Exp,ACER3_55331_Exp,...,ZNF862_643641_Exp,ZNFX1_57169_Exp,ZRANB2_9406_Exp,ZYG11B_79699_Exp,ZYX_7791_Exp,EIF2AK3_9451_Dep,MYC_4609_Dep,NQO1_1728_Dep,SF3B1_23451_Dep,SQSTM1_8878_Dep
0,ACH-000001,3.078951,2.443607,4.811985,4.746313,5.388534,1.510962,2.918386,4.514753,5.980025,...,2.629939,4.003602,6.157044,2.797013,6.821455,0.018546,0.807414,0.076613,1.000000,0.020657
1,ACH-000004,2.292782,0.713696,4.973152,4.727920,5.187055,0.000000,6.191997,3.166715,3.648465,...,1.560715,2.904966,7.344917,2.032101,7.002252,0.044907,0.999985,0.061617,1.000000,0.049385
2,ACH-000005,2.625270,0.163499,5.231509,5.802452,5.328406,0.028569,5.561632,2.464668,4.025029,...,1.700440,3.166715,7.609179,2.761285,6.826421,0.009301,1.000000,0.049535,0.994004,0.015969
3,ACH-000007,1.970854,0.070389,3.392317,4.532940,3.499527,2.386811,4.410070,4.799605,2.283922,...,2.435629,3.051372,5.645010,1.989139,6.332708,0.058868,0.999620,0.036902,0.999886,0.041706
4,ACH-000009,3.397803,0.070389,5.590662,5.454834,4.841470,0.084064,5.183883,4.221877,3.549669,...,1.395063,4.263786,5.151372,2.956057,7.853185,0.040590,0.979828,0.006602,0.973598,0.034535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,ACH-002785,3.819668,0.238787,3.730096,5.890933,5.172728,0.189034,2.695994,1.895303,2.313246,...,2.773996,4.753284,6.036064,4.173127,6.560256,0.038095,0.701928,0.161286,1.000000,0.136197
1001,ACH-002800,4.034744,1.967169,2.805292,5.292414,4.761817,0.731183,4.161081,1.910733,3.206331,...,2.408712,3.614710,5.499846,3.084064,6.596935,0.177952,0.462993,0.054260,1.000000,0.022899
1002,ACH-002834,4.133399,1.786596,3.226509,4.999098,4.737146,0.214125,3.351911,2.464668,2.799087,...,0.887525,4.932156,5.254367,2.568032,6.953498,0.002074,0.911326,0.022301,0.998623,0.013754
1003,ACH-002847,3.396434,0.400538,3.379898,4.888500,4.164304,0.042644,2.482848,3.649615,6.646451,...,1.925999,3.484138,5.189825,2.748461,7.432041,0.161273,0.704900,0.184386,0.999903,0.058351
1004,ACH-002926,3.033863,0.000000,4.672991,4.822730,4.914565,0.000000,3.509696,3.845992,3.496974,...,2.516015,3.512227,5.825531,2.776104,5.182295,0.017135,0.963046,0.022057,0.998453,0.055990

In [ ]:
# Splitting the Dataset
# features = data[['A1BG_1_Exp', 'A1CF_29974_Exp', 'A2M_2_Exp', 'A2ML1_144568_Exp', 'A3GALT2_127550_Exp', 'A4GALT_53947_Exp', 'A4GNT_51146_Exp', 'AAAS_8086_Exp', 'AACS_65985_Exp', 'AADAC_13_Exp']]
# targets = data[['EIF2AK3_9451_Dep', 'MYC_4609_Dep']]

In [ ]:
# Exclude 'DepMap_ID' column
data_without_id = data.drop(columns=['DepMap_ID'])

# Extracting Features and Targets
features = data_without_id.drop(columns=[col for col in data_without_id.columns if 'Dep' in col])
targets = data_without_id[[col for col in data_without_id.columns if 'Dep' in col]]

In [ ]:
# Exclude 'DepMap_ID' column
data_without_id = data.drop(columns=['DepMap_ID'])

# Extracting Features and Targets
features = data_without_id.drop(columns=[col for col in data_without_id.columns if 'Dep' in col])
# targets = data_without_id[[col for col in data_without_id.columns if 'Dep' in col]]
targets = data_without_id[["MYC_4609_Dep","SF3B1_23451_Dep"]]

targets

      MYC_4609_Dep  SF3B1_23451_Dep
0         0.807414         1.000000
1         0.999985         1.000000
2         1.000000         0.994004
3         0.999620         0.999886
4         0.979828         0.973598
...            ...              ...
1000      0.701928         1.000000
1001      0.462993         1.000000
1002      0.911326         0.998623
1003      0.704900         0.999903
1004      0.963046         0.998453

[1005 rows x 2 columns]

In [ ]:
# Exclude 'DepMap_ID' column
data_without_id = data.drop(columns=['DepMap_ID'])

# Extracting Features and Targets
features = data_without_id.drop(columns=[col for col in data_without_id.columns if 'Dep' in col])
# targets = data_without_id[[col for col in data_without_id.columns if 'Dep' in col]]
targets = data_without_id[["MYC_4609_Dep"]]

targets

      MYC_4609_Dep
0         0.807414
1         0.999985
2         1.000000
3         0.999620
4         0.979828
...            ...
1000      0.701928
1001      0.462993
1002      0.911326
1003      0.704900
1004      0.963046

[1005 rows x 1 columns]

In [ ]:
# Extracting Features and Targets
# features = data.drop(columns=['DepMap_ID', 'EIF2AK3_9451_Dep', 'MYC_4609_Dep'])
# targets = data[['EIF2AK3_9451_Dep', 'MYC_4609_Dep']]

In [ ]:
# Splitting the Data into Train and Test Sets
X_train, X_test, y_train, y_test = train_test_split(features, targets, test_size=0.2, random_state=42)

In [ ]:
# Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# Create and train the KNN regressor
knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train_scaled, y_train)

KNeighborsRegressor()

In [ ]:
# Make predictions
y_pred = knn.predict(X_test_scaled)

In [ ]:
# Printing Predicted Values
print('Predicted Values:', y_pred)

Predicted Values: [[0.03589271 0.9306097  0.18027774 0.99972789 0.10509783]
 [0.059011   0.97870718 0.17865449 0.99928802 0.09458712]
 [0.05179014 0.79970102 0.08801468 0.99995524 0.03466592]
 ...
 [0.15286364 0.96130479 0.06846979 0.97735024 0.05839303]
 [0.02772642 0.99435106 0.09998339 0.99071654 0.03446373]
 [0.05426658 0.99522934 0.09733104 0.99375158 0.05769948]]

In [ ]:
# Evaluating the Model
# Mean Squared Error. It is a common metric used to measure the average squared difference between the predicted and actual values in regression tasks.
# Lower values of MSE indicate better model performance, as it means the predicted values are closer to the actual values. However, MSE is sensitive to outliers since the squared differences magnify their impact on the overall error.

mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)

Mean Squared Error: 0.010354672199808035

In [ ]:
# Mean Absolute Error (MAE) measures the average absolute difference between the predicted and actual values. It gives a straightforward measure of the average prediction error. Lower MAE values indicate better accuracy.

from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)
print('Mean Absolute Error:', mae)

Mean Absolute Error: 0.05144551753048687

In [ ]:
# Calculate R-squared (coefficient of determination)

from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print('Coefficient of Determination (R-squared):', r2)

Coefficient of Determination (R-squared): -0.13671761005737365

In [ ]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)

mae = mean_absolute_error(y_test, y_pred)
print('Mean Absolute Error:', mae)

r2 = r2_score(y_test, y_pred)
print('Coefficient of Determination (R-squared):', r2)

Mean Squared Error: 0.010354672199808035
Mean Absolute Error: 0.05144551753048687
Coefficient of Determination (R-squared): -0.13671761005737365

In [ ]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)

mae = mean_absolute_error(y_test, y_pred)
print('Mean Absolute Error:', mae)

r2 = r2_score(y_test, y_pred)
print('Coefficient of Determination (R-squared):', r2)

Mean Squared Error: 0.010174077342862438
Mean Absolute Error: 0.05073805602021322
Coefficient of Determination (R-squared): -0.13969637009875674

In [ ]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)

mae = mean_absolute_error(y_test, y_pred)
print('Mean Absolute Error:', mae)

r2 = r2_score(y_test, y_pred)
print('Coefficient of Determination (R-squared):', r2)

Mean Squared Error: 0.009238298059151571
Mean Absolute Error: 0.05016967362001079
Coefficient of Determination (R-squared): -0.04917262530771136

In [ ]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)

mae = mean_absolute_error(y_test, y_pred)
print('Mean Absolute Error:', mae)

r2 = r2_score(y_test, y_pred)
print('Coefficient of Determination (R-squared):', r2)

Mean Squared Error: 0.02124689317693166
Mean Absolute Error: 0.061458569228540656
Coefficient of Determination (R-squared): 0.031053291620775636

In [ ]:
# Retrieve the 'DepMap_ID' column before splitting
depmap_id_column = data['DepMap_ID']

# Create a new DataFrame for the test set with the predicted and actual values
test_data = X_test.copy()

# Add 'DepMap_ID' column to test_data
test_data.insert(0, 'DepMap_ID', depmap_id_column.iloc[X_test.index].values)

for i, col in enumerate(targets.columns):
    pred_col = f'Pred_{col}'
    test_data[pred_col] = y_pred[:, i]
    test_data[col] = y_test.iloc[:, i].values

# Save the DataFrame to a CSV file
test_data.to_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/test_data_KNN1_01.csv", index=False)

# Display the updated DataFrame
test_data

,DepMap_ID,A1BG_1_Exp,A1CF_29974_Exp,A2M_2_Exp,A2ML1_144568_Exp,A3GALT2_127550_Exp,A4GALT_53947_Exp,A4GNT_51146_Exp,AAAS_8086_Exp,AACS_65985_Exp,...,Pred_EIF2AK3_9451_Dep,EIF2AK3_9451_Dep,Pred_MYC_4609_Dep,MYC_4609_Dep,Pred_NQO1_1728_Dep,NQO1_1728_Dep,Pred_SF3B1_23451_Dep,SF3B1_23451_Dep,Pred_SQSTM1_8878_Dep,SQSTM1_8878_Dep
926,ACH-001858,0.176323,0.056584,0.097611,0.014355,0.000000,3.035624,0.056584,5.299758,4.263034,...,0.038881,0.089924,0.921147,0.986031,0.186815,0.061362,0.999803,0.965198,0.087997,0.100194
630,ACH-000962,4.410748,0.028569,0.056584,0.000000,0.028569,1.189034,0.014355,5.620000,4.238023,...,0.048270,0.013249,0.967987,0.808635,0.155927,0.424683,0.992186,0.999715,0.098423,0.077090
682,ACH-001164,4.262283,0.000000,5.371210,0.000000,0.000000,1.765535,0.000000,5.003152,3.489286,...,0.047100,0.128009,0.976990,0.999965,0.057141,0.006208,0.997056,0.989402,0.026962,0.173517
514,ACH-000799,4.440288,0.014355,6.867773,0.014355,0.163499,0.641546,0.124328,5.484460,4.268285,...,0.057795,0.119600,0.940662,0.973706,0.228258,0.046536,0.997888,1.000000,0.153988,0.082562
365,ACH-000571,5.489928,0.000000,0.678072,0.000000,0.042644,3.016140,0.214125,5.319040,4.609400,...,0.100156,0.055957,0.952810,0.947456,0.126908,0.135590,0.978819,0.999373,0.105014,0.268415
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,ACH-000339,0.111031,0.014355,0.028569,0.000000,0.000000,1.378512,0.028569,5.497612,3.605257,...,0.038512,0.019725,0.984273,0.981174,0.106256,0.196715,0.994794,0.977665,0.053414,0.035018
778,ACH-001454,0.400538,0.000000,0.189034,0.163499,0.000000,4.678072,0.000000,4.751678,4.521051,...,0.078396,0.007032,0.985700,0.851388,0.123603,0.046067,0.983163,1.000000,0.172747,0.074650
334,ACH-000522,4.157044,0.000000,0.214125,0.000000,0.000000,2.893362,0.014355,6.321026,3.298658,...,0.044158,0.031388,0.989362,0.999722,0.072721,0.300746,0.968956,0.994450,0.032761,0.106541
210,ACH-000343,4.189034,0.042644,0.014355,0.367371,0.000000,2.304511,0.097611,5.744699,4.082362,...,0.038136,0.063896,0.989915,0.971561,0.089849,0.086851,0.997588,0.999641,0.059014,0.011019
350,ACH-000549,0.056584,0.000000,0.400538,0.111031,0.028569,5.224581,0.000000,5.139142,3.994580,...,0.062861,0.064660,0.992651,0.999956,0.080665,0.055492,0.993689,1.000000,0.061605,0.038641

In [ ]:
# Add 'DepMap_ID' column to test_data
# test_data.insert(0, 'DepMap_ID', depmap_id_column.iloc[X_test.index].values)

for i, col in enumerate(targets.columns):
    pred_col = f'Pred_{col}'
    test_data[pred_col] = y_pred[:, i]
    test_data[col] = y_test.iloc[:, i].values

# Save the DataFrame to a CSV file
test_data.to_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/test_data_KNN1_02.csv", index=False)

# Display the updated DataFrame
test_data

,DepMap_ID,A1BG_1_Exp,A1CF_29974_Exp,A2M_2_Exp,A2ML1_144568_Exp,A3GALT2_127550_Exp,A4GALT_53947_Exp,A4GNT_51146_Exp,AAAS_8086_Exp,AACS_65985_Exp,...,ZXDC_79364_Exp,ZYG11A_440590_Exp,ZYG11B_79699_Exp,ZYX_7791_Exp,ZZEF1_23140_Exp,ZZZ3_26009_Exp,Pred_MYC_4609_Dep,MYC_4609_Dep,Pred_SF3B1_23451_Dep,SF3B1_23451_Dep
926,ACH-001858,0.176323,0.056584,0.097611,0.014355,0.000000,3.035624,0.056584,5.299758,4.263034,...,2.889474,0.815575,2.976364,7.199967,3.465974,4.780310,0.921147,0.986031,0.999803,0.965198
630,ACH-000962,4.410748,0.028569,0.056584,0.000000,0.028569,1.189034,0.014355,5.620000,4.238023,...,3.364572,2.307429,2.980025,6.212569,3.214125,3.919340,0.967987,0.808635,0.992186,0.999715
682,ACH-001164,4.262283,0.000000,5.371210,0.000000,0.000000,1.765535,0.000000,5.003152,3.489286,...,2.711495,0.333424,2.495695,4.735522,2.107688,3.363171,0.976990,0.999965,0.997056,0.989402
514,ACH-000799,4.440288,0.014355,6.867773,0.014355,0.163499,0.641546,0.124328,5.484460,4.268285,...,4.251719,0.475085,2.077243,7.966477,4.179511,3.481557,0.940662,0.973706,0.997888,1.000000
365,ACH-000571,5.489928,0.000000,0.678072,0.000000,0.042644,3.016140,0.214125,5.319040,4.609400,...,3.526069,0.000000,3.114367,6.934281,4.079805,4.527946,0.952810,0.947456,0.978819,0.999373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,ACH-000339,0.111031,0.014355,0.028569,0.000000,0.000000,1.378512,0.028569,5.497612,3.605257,...,3.135863,2.319040,2.367371,7.258236,2.841973,4.584361,0.984273,0.981174,0.994794,0.977665
778,ACH-001454,0.400538,0.000000,0.189034,0.163499,0.000000,4.678072,0.000000,4.751678,4.521051,...,2.754888,1.220330,2.459432,5.038261,2.782409,2.657640,0.985700,0.851388,0.983163,1.000000
334,ACH-000522,4.157044,0.000000,0.214125,0.000000,0.000000,2.893362,0.014355,6.321026,3.298658,...,3.442280,2.761285,3.238787,7.097295,4.590362,4.649041,0.989362,0.999722,0.968956,0.994450
210,ACH-000343,4.189034,0.042644,0.014355,0.367371,0.000000,2.304511,0.097611,5.744699,4.082362,...,3.607626,3.411426,3.869871,3.674687,2.611172,4.669027,0.989915,0.971561,0.997588,0.999641
350,ACH-000549,0.056584,0.000000,0.400538,0.111031,0.028569,5.224581,0.000000,5.139142,3.994580,...,4.050502,0.464668,2.176323,5.941811,3.204767,3.982765,0.992651,0.999956,0.993689,1.000000

In [ ]:
# Retrieve the 'DepMap_ID' column before splitting
depmap_id_column = data['DepMap_ID']

# Create a new DataFrame for the test set with the predicted and actual values
test_data = X_test.copy()

# Add 'DepMap_ID' column to test_data
test_data.insert(0, 'DepMap_ID', depmap_id_column.iloc[X_test.index].values)

target_col = "MYC_4609_Dep"  # Replace with the name of your target column

pred_col = f'Pred_{target_col}'
test_data[pred_col] = y_pred[:, 0]  # Assign predicted values to the new column

actual_col = target_col
test_data[actual_col] = y_test.values  # Assign actual values to the target column

# Save the DataFrame to a CSV file
test_data.to_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/test_data_KNN1_02.csv", index=False)

# Display the updated DataFrame
test_data

,DepMap_ID,A1BG_1_Exp,A1CF_29974_Exp,A2M_2_Exp,A2ML1_144568_Exp,A3GALT2_127550_Exp,A4GALT_53947_Exp,A4GNT_51146_Exp,AAAS_8086_Exp,AACS_65985_Exp,...,ZXDA_7789_Exp,ZXDB_158586_Exp,ZXDC_79364_Exp,ZYG11A_440590_Exp,ZYG11B_79699_Exp,ZYX_7791_Exp,ZZEF1_23140_Exp,ZZZ3_26009_Exp,Pred_MYC_4609_Dep,MYC_4609_Dep
926,ACH-001858,0.176323,0.056584,0.097611,0.014355,0.000000,3.035624,0.056584,5.299758,4.263034,...,0.992768,2.451541,2.889474,0.815575,2.976364,7.199967,3.465974,4.780310,0.921147,0.986031
630,ACH-000962,4.410748,0.028569,0.056584,0.000000,0.028569,1.189034,0.014355,5.620000,4.238023,...,1.599318,2.538538,3.364572,2.307429,2.980025,6.212569,3.214125,3.919340,0.967987,0.808635
682,ACH-001164,4.262283,0.000000,5.371210,0.000000,0.000000,1.765535,0.000000,5.003152,3.489286,...,0.495695,1.244887,2.711495,0.333424,2.495695,4.735522,2.107688,3.363171,0.976990,0.999965
514,ACH-000799,4.440288,0.014355,6.867773,0.014355,0.163499,0.641546,0.124328,5.484460,4.268285,...,0.807355,1.475085,4.251719,0.475085,2.077243,7.966477,4.179511,3.481557,0.940662,0.973706
365,ACH-000571,5.489928,0.000000,0.678072,0.000000,0.042644,3.016140,0.214125,5.319040,4.609400,...,0.516015,1.918386,3.526069,0.000000,3.114367,6.934281,4.079805,4.527946,0.952810,0.947456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,ACH-000339,0.111031,0.014355,0.028569,0.000000,0.000000,1.378512,0.028569,5.497612,3.605257,...,0.505891,1.769772,3.135863,2.319040,2.367371,7.258236,2.841973,4.584361,0.984273,0.981174
778,ACH-001454,0.400538,0.000000,0.189034,0.163499,0.000000,4.678072,0.000000,4.751678,4.521051,...,1.104337,1.847997,2.754888,1.220330,2.459432,5.038261,2.782409,2.657640,0.985700,0.851388
334,ACH-000522,4.157044,0.000000,0.214125,0.000000,0.000000,2.893362,0.014355,6.321026,3.298658,...,0.823749,1.879706,3.442280,2.761285,3.238787,7.097295,4.590362,4.649041,0.989362,0.999722
210,ACH-000343,4.189034,0.042644,0.014355,0.367371,0.000000,2.304511,0.097611,5.744699,4.082362,...,5.763943,5.212180,3.607626,3.411426,3.869871,3.674687,2.611172,4.669027,0.989915,0.971561
350,ACH-000549,0.056584,0.000000,0.400538,0.111031,0.028569,5.224581,0.000000,5.139142,3.994580,...,1.448901,1.974529,4.050502,0.464668,2.176323,5.941811,3.204767,3.982765,0.992651,0.999956

In [ ]:
# Retrieve the 'DepMap_ID' column before splitting
depmap_id_column = data['DepMap_ID']

# Create a new DataFrame for the test set with the predicted and actual values
test_data = X_test.copy()

# Add 'DepMap_ID' column to test_data
test_data.insert(0, 'DepMap_ID', depmap_id_column.iloc[X_test.index].values)

target_col = "MYC_4609_Dep"  # Replace with the name of your target column

pred_col = f'Pred_{target_col}'
test_data[pred_col] = y_pred[:, 0]  # Assign predicted values to the new column

actual_col = target_col
test_data[actual_col] = y_test.values  # Assign actual values to the target column

# Save the DataFrame to a CSV file
test_data.to_csv("/content/drive/MyDrive/Colab Notebooks/DeepDEP/test_data_KNN1_02.csv", index=False)

# Display the updated DataFrame
test_data

,DepMap_ID,A1BG_1_Exp,A1CF_29974_Exp,A2M_2_Exp,A2ML1_144568_Exp,A3GALT2_127550_Exp,A4GALT_53947_Exp,A4GNT_51146_Exp,AAAS_8086_Exp,AACS_65985_Exp,...,ZXDA_7789_Exp,ZXDB_158586_Exp,ZXDC_79364_Exp,ZYG11A_440590_Exp,ZYG11B_79699_Exp,ZYX_7791_Exp,ZZEF1_23140_Exp,ZZZ3_26009_Exp,Pred_MYC_4609_Dep,MYC_4609_Dep
926,ACH-001858,0.176323,0.056584,0.097611,0.014355,0.000000,3.035624,0.056584,5.299758,4.263034,...,0.992768,2.451541,2.889474,0.815575,2.976364,7.199967,3.465974,4.780310,0.999803,0.965198
630,ACH-000962,4.410748,0.028569,0.056584,0.000000,0.028569,1.189034,0.014355,5.620000,4.238023,...,1.599318,2.538538,3.364572,2.307429,2.980025,6.212569,3.214125,3.919340,0.992186,0.999715
682,ACH-001164,4.262283,0.000000,5.371210,0.000000,0.000000,1.765535,0.000000,5.003152,3.489286,...,0.495695,1.244887,2.711495,0.333424,2.495695,4.735522,2.107688,3.363171,0.997056,0.989402
514,ACH-000799,4.440288,0.014355,6.867773,0.014355,0.163499,0.641546,0.124328,5.484460,4.268285,...,0.807355,1.475085,4.251719,0.475085,2.077243,7.966477,4.179511,3.481557,0.997888,1.000000
365,ACH-000571,5.489928,0.000000,0.678072,0.000000,0.042644,3.016140,0.214125,5.319040,4.609400,...,0.516015,1.918386,3.526069,0.000000,3.114367,6.934281,4.079805,4.527946,0.978819,0.999373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,ACH-000339,0.111031,0.014355,0.028569,0.000000,0.000000,1.378512,0.028569,5.497612,3.605257,...,0.505891,1.769772,3.135863,2.319040,2.367371,7.258236,2.841973,4.584361,0.994794,0.977665
778,ACH-001454,0.400538,0.000000,0.189034,0.163499,0.000000,4.678072,0.000000,4.751678,4.521051,...,1.104337,1.847997,2.754888,1.220330,2.459432,5.038261,2.782409,2.657640,0.983163,1.000000
334,ACH-000522,4.157044,0.000000,0.214125,0.000000,0.000000,2.893362,0.014355,6.321026,3.298658,...,0.823749,1.879706,3.442280,2.761285,3.238787,7.097295,4.590362,4.649041,0.968956,0.994450
210,ACH-000343,4.189034,0.042644,0.014355,0.367371,0.000000,2.304511,0.097611,5.744699,4.082362,...,5.763943,5.212180,3.607626,3.411426,3.869871,3.674687,2.611172,4.669027,0.997588,0.999641
350,ACH-000549,0.056584,0.000000,0.400538,0.111031,0.028569,5.224581,0.000000,5.139142,3.994580,...,1.448901,1.974529,4.050502,0.464668,2.176323,5.941811,3.204767,3.982765,0.993689,1.000000